<a href="https://colab.research.google.com/github/liberato10/DianneFiltering/blob/main/DianneFilteringPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [9]:
df_bike = pd.read_csv('https://raw.githubusercontent.com/liberato10/DianneFiltering/main/RailsToTrails_National%20Count%20Data_week.xlsx%20-%20Pedestrian%20Counts%20(14%20counters)%20(1).csv')

df_bike.head()

,Timeframe,Week of,2019 counts (14 counters),2020 counts (14 counters),Change 2019-2020
0,Week 1,12/30/2020,68957,93654,36%
1,Week 2,1/6/2020,34778,46964,35%
2,Week 3,1/13/2020,32065,38302,19%
3,Week 4,1/20/2020,35016,41506,19%
4,Week 5,1/27/2020,33627,46335,38%

In [16]:
df_data = (df_bike[df_bike['Week of'] >= '31-July'])
df_data.head()

,Timeframe,Week of,2019 counts (14 counters),2020 counts (14 counters),Change 2019-2020
14,Week 15,4/6/2020,83893,107420,28%
15,Week 16,4/13/2020,71677,122291,71%
16,Week 17,4/20/2020,87834,106246,21%
17,Week 18,4/27/2020,88284,109459,24%
18,Week 19,5/4/2020,94980,109391,15%

In [14]:
df_fil = df_bike ['Week of'] >= '31-July'
df_fil.head()

0    False
1    False
2    False
3    False
4    False
Name: Week of, dtype: bool

In [15]:
df_bike.loc[df_fil].head()

,Timeframe,Week of,2019 counts (14 counters),2020 counts (14 counters),Change 2019-2020
14,Week 15,4/6/2020,83893,107420,28%
15,Week 16,4/13/2020,71677,122291,71%
16,Week 17,4/20/2020,87834,106246,21%
17,Week 18,4/27/2020,88284,109459,24%
18,Week 19,5/4/2020,94980,109391,15%

In [17]:
df = df_bike.loc[df_fil, :]
df['Week of'].value_counts()

4/6/2020     1
4/13/2020    1
9/21/2020    1
9/14/2020    1
9/7/2020     1
8/31/2020    1
8/24/2020    1
8/17/2020    1
8/10/2020    1
8/3/2020     1
7/27/2020    1
7/20/2020    1
7/13/2020    1
7/6/2020     1
6/29/2020    1
6/22/2020    1
6/15/2020    1
6/8/2020     1
6/1/2020     1
5/25/2020    1
5/18/2020    1
5/11/2020    1
5/4/2020     1
4/27/2020    1
4/20/2020    1
9/28/2020    1
Name: Week of, dtype: int64

In [18]:
df_bike['Change 2019-2020'].value_counts()

19%     4
32%     3
4%      2
15%     2
21%     2
25%     2
91%     2
59%     1
34%     1
14%     1
16%     1
17%     1
40%     1
-7%     1
31%     1
9%      1
75%     1
-3%     1
48%     1
36%     1
-16%    1
29%     1
35%     1
-41%    1
24%     1
71%     1
28%     1
80%     1
54%     1
287%    1
271%    1
-2%     1
45%     1
58%     1
38%     1
106%    1
Name: Change 2019-2020, dtype: int64

In [19]:
df_bike = df_bike.loc[df_fil, :]

In [20]:
df_bike['Change 2019-2020'].value_counts()

21%     2
15%     2
19%     2
28%     1
9%      1
59%     1
34%     1
14%     1
16%     1
4%      1
40%     1
-7%     1
32%     1
48%     1
-3%     1
71%     1
25%     1
17%     1
29%     1
-16%    1
-41%    1
24%     1
31%     1
Name: Change 2019-2020, dtype: int64

In [21]:
df.head()

,Timeframe,Week of,2019 counts (14 counters),2020 counts (14 counters),Change 2019-2020
14,Week 15,4/6/2020,83893,107420,28%
15,Week 16,4/13/2020,71677,122291,71%
16,Week 17,4/20/2020,87834,106246,21%
17,Week 18,4/27/2020,88284,109459,24%
18,Week 19,5/4/2020,94980,109391,15%